server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
        - id : r2
          uri : http://INVENTORY-SERVICE
          predicates:
            - Path=/products/**

    discovery:
      enabled: false
