spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: r1
              uri: http://localhost:8080
              predicates:
                - Path = /cutomers/**
            - id: r2
              uri: http://localhost:8081
              predicates:
                - Path = /products/**


